[package]
version = "0.1.0"
title = "RAMBO Isaac Lab Tasks"
author = "RAMBO Developers"
maintainer = "RAMBO Developers"
description = "RAMBO quadruped DirectRL tasks for Isaac Lab."
repository = "https://github.com/JalenLoong/RAMBO_Data"
category = "robotics"
keywords = ["isaaclab", "rambo", "quadruped", "robotics"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_physx" = {}

[[python.module]]
name = "rambo"
