#!/usr/bin/env bash
# Run a RAMBO Python command with the pinned venv's CUDA libraries discoverable.
#
# Examples:
#   scripts/rambo/run.sh scripts/rambo/validate.py --help
#   scripts/rambo/run.sh -m pytest -q tests/rambo/test_qpth_contract.py

set -euo pipefail

readonly VENV_DIR="${RAMBO_VENV:-/workspace/venvs/rambo51}"
readonly PYTHON="${VENV_DIR}/bin/python"

if [[ "$#" -eq 0 ]]; then
    echo "Usage: $0 <Python script or Python arguments>" >&2
    exit 2
fi
if [[ ! -x "${PYTHON}" ]]; then
    echo "RAMBO Python 3.11 venv was not found: ${PYTHON}" >&2
    echo "Run bash scripts/setup_isaacsim51.sh first or set RAMBO_VENV." >&2
    exit 1
fi

readonly PYTHON_VERSION="$("${PYTHON}" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
readonly TORCH_LIB_DIR="${VENV_DIR}/lib/python${PYTHON_VERSION}/site-packages/torch/lib"
readonly CUDA_NVRTC_LIB_DIR="${VENV_DIR}/lib/python${PYTHON_VERSION}/site-packages/nvidia/cuda_nvrtc/lib"
if [[ ! -f "${TORCH_LIB_DIR}/libtorch_cuda_linalg.so" ]]; then
    echo "Pinned PyTorch CUDA libraries were not found in ${TORCH_LIB_DIR}" >&2
    exit 1
fi
if [[ ! -f "${CUDA_NVRTC_LIB_DIR}/libnvrtc-builtins.so.12.8" ]]; then
    echo "Pinned CUDA 12.8 NVRTC libraries were not found in ${CUDA_NVRTC_LIB_DIR}" >&2
    exit 1
fi

export PYTHONNOUSERSITE=1
# Isaac Sim 5.1 wheels may carry extension ``.pyc`` files generated by a
# different Python 3.11 micro release.  On the target 3.11.15 interpreter one
# such cache raised ``bad marshal data`` before RAMBO's ContactSensor could
# load.  Keep generated bytecode outside the immutable wheel, so the runtime
# compiles source with this interpreter.  Operators can override the cache
# location when /tmp is unsuitable.
export PYTHONPYCACHEPREFIX="${RAMBO_PYCACHE_PREFIX:-/tmp/rambo51-pycache}"
# Torch resolves most wheel-bundled CUDA dependencies through RPATH, but its
# runtime compiler dlopens NVRTC builtins by soname.  Put the matching cu128
# wheel directory first so JIT kernels used by Isaac Lab math can compile.
export LD_LIBRARY_PATH="${TORCH_LIB_DIR}:${CUDA_NVRTC_LIB_DIR}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
exec "${PYTHON}" "$@"
